version: '3.4'

services:

  webapi:
    env_file: ".env"
    container_name: "webapi"
    hostname: "webapi"
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    volumes:
        - "aspnet_keys_volume:/root/.aspnet/DataProtection-Keys"
    ports:
      - "5000:80"
    networks:
      - "reviewer"
    restart: unless-stopped

  mssql:
    container_name: "mssql"
    hostname: "mssql"
    image: mcr.microsoft.com/mssql/server
    ports:
      - "7070:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - "mssql_volume:/var/opt/mssql"
    networks:
      - "reviewer"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P${MSSQL_SA_PASSWORD}", "-Q", "select 1"]
      interval: 10s
      retries: 3
    restart: unless-stopped

volumes:
  mssql_volume:
    name: "mssql_volume"
  aspnet_keys_volume:
    name: "aspnet_keys_volume"

networks:
  reviewer:
    name: "reviewer"